---
# -----------------
# YAML Templates
# -----------------

# ------------------------
# Jobs configuration
# ------------------------
jobs:
  include:
    # ---------------------------------------
    # Unit Tests & Linters
    # ---------------------------------------
    - stage: Unit Tests & Linters
      name: Unit Tests & ESLint
      dist: trusty
      language: java
      jdk: oraclejdk8
      sudo: false
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
      install:
        - cd $TRAVIS_BUILD_DIR/kuzzle-sdk-base
        - gradle assemble
      script:
        - gradle check
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    # ---------------------------------------
    # Builds
    # ---------------------------------------
    - stage: Builds
      name: Build SDK Java
      language: java
      jdk: oraclejdk8
      sudo: false
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
      install:
        - cd $TRAVIS_BUILD_DIR/kuzzle-sdk-base
        - gradle assemble
        - cd $TRAVIS_BUILD_DIR/kuzzle-sdk-java
        - gradle assemble
      script:
        - gradle build

# ------------------------
# Stages configuration
# ------------------------
stages:
  - name: Unit Tests
    if: type =~ /(cron|push|pull_request)/ AND branch =~ /^master|[0-9]+-(dev|stable)$/
  - name: Builds
    if: type =~ /(cron|push|pull_request)/ AND branch =~ /^master|[0-9]+-(dev|stable)$/

# ---------------------------------------
# Notifications
# ---------------------------------------
notifications:
  slack:
    rooms:
      - secure: "ACjz4TJEYBEzmwVOYrCNnr4+jC0FaX+qh150QacYGIgaQYL+U3xLEQmWNlZ3oxaPPMDAk42m+diHolqNwh6qsOWaPSWRlGfLKhHLSzRI98bhF7HQ+3eLMYmx7y7SKwRzyRjus0jgxp0Kc2mq0nhKqv+7rarQtIgWlC1PLrzZ35CUbUlqYSoeYAlXoyDB1eZgYsvjt+eC5yCvGePsfKbupWC2/hIVl+qZ+9AhVmOfiMv7daFW29Vu300aoY+0IqwX7jHGcmHn/7QCRsx0IBy/SL24TzfSV9SUSnbjK4fTrcrhjYDEZdH1lpvDtvr50GgkrTjy1wPVz8XIyCZ7LZolylkx+nR1MWyvum20QRFub2Qhz/+rS+OFiQZ8H01BPuklLUTSQhBksfpGBck3d2yNLiTqGEVWYTnZ9mkCnMQ3BzJXEF04KLHG7wYn2rk6wjPghVmFQH5GMsxM5v33CFgcNzp6lRJOX9CmjZosck6o9SA0WlazHH/CLWWKk1wrQ1ygDayW5m+N/o58UIxgW2LIUlp4tV1z/bRtO2yTd020yWchlKPVmf1A5OMfigJNMRsQGNZNadS7qA2M394OJw3/Hg+0EVF8gai/V8FRijmkxmhYyCIYMcjaGwx8JxfoMrRKcM76haBAhg0JQxsSVKzyXfONGzd5DXjcxSGZ2wuEdu0="
    on_success: never
    on_failure: always
